create table public.compatibility_questions (
  code text null,
  multi_select boolean not null,
  section_id bigint null,
  label jsonb null,
  pos smallint not null,
  id bigint generated by default as identity not null,
  constraint compatibility_questions_pkey primary key (id),
  constraint compatibility_questions_order_key unique (pos),
  constraint questions_code_key unique (code),
  constraint questions_group_id_fkey foreign KEY (section_id) references compatibility_sections (id)
) TABLESPACE pg_default;