create table public.compatibility_options (
  value numeric(3, 2) not null,
  label jsonb null,
  description jsonb null,
  id bigint generated by default as identity not null,
  question_id bigint null,
  constraint compatibility_options_pkey primary key (id),
  constraint compatibility_options_question_id_fkey foreign KEY (question_id) references compatibility_questions (id) on delete CASCADE,
  constraint question_options_value_numeric_check check (
    (
      (value >= (0)::numeric)
      and (value <= (1)::numeric)
    )
  )
) TABLESPACE pg_default;