create table public.compatibility_answers (
  id bigint generated by default as identity not null,
  profile_id uuid not null,
  option_id bigint not null,
  constraint compatibility_answers_pkey primary key (id),
  constraint profile_answers_option_id_fkey foreign KEY (option_id) references compatibility_options (id) on delete CASCADE,
  constraint profile_answers_profile_id_fkey foreign KEY (profile_id) references profiles (id) on delete CASCADE
) TABLESPACE pg_default;

create trigger compatibility_answer_insert_check BEFORE INSERT on compatibility_answers for EACH row
execute FUNCTION compatibility_answer_check ();