create table public.countries (
  id bigint not null,
  name text null,
  iso3 text null,
  iso2 text null,
  numeric_code bigint null,
  phonecode bigint null,
  capital text null,
  currency text null,
  currency_name text null,
  currency_symbol text null,
  tld text null,
  native text null,
  population bigint null,
  region text null,
  region_id bigint null,
  subregion text null,
  subregion_id bigint null,
  nationality text null,
  timezones text null,
  latitude double precision null,
  longitude double precision null,
  emoji text null,
  "emojiU" text null,
  "wiki_dataId" text null,
  flag_url text null,
  constraint countries_pkey primary key (id),
  constraint countries_id_key unique (id)
) TABLESPACE pg_default;